name: Build Trial for GitHub Pages

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace entire content of next.config.js for-github-workflows.next.config.js
        run: |
          cat for-github-workflows.next.config.js > next.config.js

      - name: Set repository name
        id: extract_repo
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Set up pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Set up pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and Export
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
        run: |
          pnpm build
          npx next export
